version: '3.9'
services:
 app:
    build: .
    container_name: app
    image: app:latest
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - mysql
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin123
      - MYSQL_PASSWORD=admin123
      - MYSQL_DB=routermanage

 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

 mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'routermanage'
      MYSQL_USER: 'admin123'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
 esdata:
    driver: local
 my-db:
    driver: local
